apiVersion: v1
kind: ConfigMap
metadata:
  name: recon-cms-config
  namespace: recon-staging
  labels:
    app: recon-cms
    environment: staging
data:
  VITE_PORT: "3039"
  VITE_API_BASE_URL: "http://171.244.63.217:30180"
